### ISSUE TITLE
not is windows but macos

### ISSUE THREAD

**Issue by gretel** [chlorm/elvish-ssh#2]
```
$ agent:init-instance
Exception: variable $platform:windows not found
Traceback:
  /Users/tom/.local/share/elvish/lib/github.com/chlorm/elvish-ssh/agent.elv, line 124:
        if (not $platform:windows) {
  [tty 8], line 1:
    agent:init-instance
```

shouldbe `is-windows`?

**Comment by codyopel** [comment]
@gretel  It should be a little closer to being in a working state now, I fixed some of they more obvious issues I found.

**Comment by gretel** [comment]
> @gretel It should be a little closer to being in a working state now, I fixed some of they more obvious issues I found.

thanks! but 😄 

```
$ agent:init-instance
Exception: Cache directory does not exist, session not initialized
Traceback:
  /Users/tom/.local/share/elvish/lib/github.com/chlorm/elvish-ssh/agent.elv, line 81:
            fail 'Cache directory does not exist, session not initialized'
  /Users/tom/.local/share/elvish/lib/github.com/chlorm/elvish-ssh/agent.elv, line 134:
        cache-read
  [tty 40], line 1:
    agent:init-instance
```

btw, `README.md` should have `epm:install` instead of `:imstall`.

**Comment by codyopel** [comment]
You have to call `agent:init-session` once per user login session.  It sets up the `XDG_RUNTIME_DIR/agent-auto` directory which `agent:init-instance` reads from.
